version: '3.8'

services:
  app:
    image: $${{ secrets.DOCKER_USERNAME }}/app:latest
    container_name: app-container
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - MONGO_URI=mongodb://mongo:27017/app
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    container_name: mongo-container
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: